### ISSUE TITLE
[studio] Page crashes on load

### ISSUE THREAD

**Issue by zachwolf** [codemod-com/codemod#1114]
### Issue Description

Select one of:
[ ] Generated codemod is not correct
[x] Bug in Codemod Studio
[ ] UI/UX improvement request
[ ] Feature request

Trying to load the studio page crashes on load

![studioerror-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/75e2d6af-0766-4de4-841e-d3140243aff0)

```
TypeError: ("string"==typeof e?function(e){let t=new eF;return t.acceptChunk(e),t.finish()}(e):v.Hf(e)?function(e){let t;let i=new eF;for(;"string"==typeof(t=e.read());)i.acceptChunk(t);return i.finish()}(e):e).create is not a function. (In '("string"==typeof e?function(e){let t=new eF;return t.acceptChunk(e),t.finish()}(e):v.Hf(e)?function(e){let t;let i=new eF;for(;"string"==typeof(t=e.read());)i.acceptChunk(t);return i.finish()}(e):e).create(t)', '("string"==typeof e?function(e){let t=new eF;return t.acceptChunk(e),t.finish()}(e):v.Hf(e)?function(e){let t;let i=new eF;for(;"string"==typeof(t=e.read());)i.acceptChunk(t);return i.finish()}(e):e).create' is undefined)
```

### Steps to Reproduce

1. Navigate to [Codemod Studio](https://codemod.com/studio)

### Actual Results

Page crashes

### Expected Results

Page does not crash

### Technical details

- Tested on Mac 14.5 in both Safari 17.5 (19618.2.12.11.6) and Chrome 126.0.6478.183

Thank you!

**Comment by alexbit-codemod** [comment]
thanks for reporting this issue zach. until we get this fixed, try this studio link https://go.codemod.com/sme-input
my guess is that you have some non-parsable code in the studio editors and the page crashes. we will get this fixed soon.

**Comment by mohab-sameh** [comment]
@all-contributors add @zachwolf for bug

**Comment by with-heart** [comment]
> my guess is that you have some non-parsable code in the studio editors and the page crashes.

Just want to note that it crashed with the same error my first time ever signing in and using the studio

**Comment by alexbit-codemod** [comment]
wow. this is bad. and we are looking into this now... @grzim on it

**Comment by grzim** [comment]
Fix pushed 👍

**Comment by alexbit-codemod** [comment]
thanks again for reporting this issue @zachwolf .

**Comment by zachwolf** [comment]
confirmed it's working for me now, that was super quick - thank you!
