### ISSUE TITLE
feat(cli): improve messaging - Incorrect `--engine` value reports unhelpful error

### ISSUE THREAD

**Issue by with-heart** [codemod-com/codemod#1119]
Related to #1118, I ran the cli with `--engine test` just to see if it would tell me what the correct options are. Instead I just received the error `Invalid type`.

It would be helpful if the cli helped me fix my problem by listing the valid types :)

**Comment by alexbit-codemod** [comment]
wow. your attention to details is exceptional. i love it. thank you so much for sharing these. really appreciate that.

**Comment by with-heart** [comment]
Thank you so much, that really means a lot ❤️

**Comment by r4zendev** [comment]
Hey-hey, @with-heart, thanks for this UX improvement suggestion, we have removed the `--engine` flag during standalone local codemod runs in favor of a GUI implementation asking you to choose one of the engines we support to make the experience smoother. It looks something like this:

<img width="590" alt="image" src="https://github.com/user-attachments/assets/cfabb6ee-b9cb-4c84-83e5-5736f2f1e585">

Let us know if you find any other issues you'd like us to take action against!
