### ISSUE TITLE
[studio] Message textarea "Send message" button covers text

### ISSUE THREAD

**Issue by with-heart** [codemod-com/codemod#1123]
### Issue Description

Select one of:
[ ] Generated codemod is not correct
[ ] Bug in Codemod Studio
[x] UI/UX improvement request
[ ] Feature request

### Actual Results

<img width="508" alt="image" src="https://github.com/user-attachments/assets/9ab5e293-8862-41ca-92e0-69d05d395d1e">

### Expected Results

<img width="505" alt="image" src="https://github.com/user-attachments/assets/0842cb72-1a36-4ad5-9965-797c601936fe">

### Technical details

Since the "Send message" button is absolutely positioned, the `textarea` should have a larger `padding-right` value to prevent its text content from being covered by the button.

**Comment by alexbit-codemod** [comment]
thanks for paying attention to the details. we will get to this. low pri, low effort.

**Comment by poswalsameer** [comment]
Is anyone working on this now? If not, I would like to start working on this!

**Comment by mohab-sameh** [comment]
@poswalsameer would you like to pick this up if the issue still persists? If not, I can close the issue as stale.

**Comment by poswalsameer** [comment]
> @poswalsameer would you like to pick this up if the issue still persists? If not, I can close the issue as stale.

Sure, will start working on it. If it has been resolved, I will let you know and you can close it then.

**Comment by mohab-sameh** [comment]
Okay awesome! Thanks a lot @poswalsameer. Will stay tuned to this issue so I can feature you in our list of contributors once an issue is pushed.

**Comment by poswalsameer** [comment]
> Okay awesome! Thanks a lot @poswalsameer. Will stay tuned to this issue so I can feature you in our list of contributors once an issue is pushed.

Yep, also in my previous contribution. I suggested having a local dev setup guide to help the new contributors in setting up this project. Ig I suggested this to @alexbit-codemod. So if possible, please add this so it could be helpful to everyone who's contributing to codemod.

**Comment by alexbit-codemod** [comment]
we are making some considerable revamp to our platform and will encourage more contribution with better guidelines once v2 is ready. thanks @poswalsameer

**Comment by poswalsameer** [comment]
Hi @mohab-sameh, I have added the PR along with a screenshot for your reference. It was a one-line fix, so yeah sorted.

**Comment by mohab-sameh** [comment]
@poswalsameer Awesome! Closing as completed.
@all-contributors add @poswalsameer for bugs
