### ISSUE TITLE
[studio] Add title attribute to make it clear what assistant response arrow button does

### ISSUE THREAD

**Issue by with-heart** [codemod-com/codemod#1124]
### Issue Description

Select one of:
[ ] Generated codemod is not correct
[ ] Bug in Codemod Studio
[x] UI/UX improvement request
[ ] Feature request

The arrow button shown in the image below doesn't have a `title` attribute so it's unclear what it actually does.

<img width="746" alt="image" src="https://github.com/user-attachments/assets/892863c7-e122-472f-adfe-3aea32bb9bef">

### Actual Results

Unable to determine what the function of the button is.

### Expected Results

The button has a `title` attribute, allowing me to hover the button and see a description of what it does. Maybe "Copy to Codemod" or "Replace Codemod text"?

**Comment by mohab-sameh** [comment]
Good point @with-heart. Thanks for reporting this!

**Comment by grzim** [comment]
@with-heart I added tooltips on hover 👍 
https://github.com/codemod-com/codemod/pull/1156

**Comment by with-heart** [comment]
Yall are awesome ❤️

**Comment by mohab-sameh** [comment]
@all-contributors add @with-heart for bugs
