### ISSUE TITLE
[codemod][FP/FN] nuxt/4/migration-recipe

### ISSUE THREAD

**Issue by Shana-AE** [codemod-com/codemod#1146]
if I select all then I got
![image](https://github.com/user-attachments/assets/a58c7c59-b8dd-40cb-9f28-97e6c028767f)

if I unselect the `nuxt/4/template-compilation-changes` I got
![image](https://github.com/user-attachments/assets/37ad5788-e0a9-4454-8a9d-a0136da82fb0)

and error log is just
- CLI version: 0.11.35
  - Node version: 20.12.2
  - OS: Darwin 23.5.0 arm64

**Comment by DmytroHryshyn** [comment]
@Shana-AE Thank you for reporting this issue, we will look into it shortly

**Comment by DmytroHryshyn** [comment]
@Shana-AE Issue is fixed in `codemod@0.12.2` release.
