### ISSUE TITLE
fix(auth UI): fix the color for Clerk UI component

### ISSUE THREAD

**Issue by manishjha-04** [codemod-com/codemod#1197]
> **In the Manage Account Section I am not able to view Profile, Security and update Profile Option.**

![Screenshot 2024-08-07 222502](https://github.com/user-attachments/assets/9c56ad65-d536-4d37-86cf-d133c5b07dd1)

**Comment by alexbit-codemod** [comment]
manish! thanks for reporting this issue. will have the team look into this based on its priority.

**Comment by mohab-sameh** [comment]
@all-contributors add @manishjha-04 for bugs

**Comment by poswalsameer** [comment]
Hi @alexbit-codemod, I would like to work on this issue. Can you assign this to me?

**Comment by poswalsameer** [comment]
One more thing @alexbit-codemod, while setting up the codebase locally, I found out that there's no guide for contributors on how to setup the project on their local machine. This would help many new people looking to contribute to codemod. Thanks.

**Comment by alexbit-codemod** [comment]
great point. notified the team. thanks.

**Comment by poswalsameer** [comment]
Hi @alexbit-codemod, I have raised PR #1352 which solves this issue of the wrong font color used in the clerk component. The issue arises because of the theme difference between the original component of Clerk and the component used in the codemod. Please review the PR so it can be merged.

**Comment by poswalsameer** [comment]
> Hi @alexbit-codemod, I have raised PR #1352 which solves this issue of the wrong font color used in the clerk component. The issue arises because of the theme difference between the original component of Clerk and the component used in the codemod. Please review the PR so it can be merged.

Also, please try to have a CONTRIBUTING.md file as soon as possible so it can help new contributors to set up the codebase easily through docker as well as normal method too.

**Comment by alexbit-codemod** [comment]
@all-contributors add @poswalsameer for code

**Comment by mohab-sameh** [comment]
thanks for the great feedback @poswalsameer. I'll improve the instructions in [CONTRIBUTING.md](https://github.com/codemod-com/codemod/blob/main/CONTRIBUTING.md). We also need to improve the contributing local dev experience itself too.

**Comment by poswalsameer** [comment]
> thanks for the great feedback @poswalsameer. I'll improve the instructions in [CONTRIBUTING.md](https://github.com/codemod-com/codemod/blob/main/CONTRIBUTING.md). We also need to improve the contributing local dev experience itself too.

It's my pleasure. I look forward to contributing more to codemod.
