### ISSUE TITLE
bug: issue running codemod on windows/wsl

### ISSUE THREAD

**Issue by kevincam3** [codemod-com/codemod#1233]
### Faulty codemod

1. nuxt/4/migration-recipe

### Sample code snippets
npx codemod@latest nuxt/4/migration-recipe

#### Original

```ts
npx codemod@latest nuxt/4/migration-recipe
[Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files]
```

#### Expected

```ts
No errors
```

#### Actual

```ts
[Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files]
```

### Estimated impact
Numbers about your specific codemod run:

- Total number of files/instances transformed: 0
- Number of files/instances missed by the codemod (FN): All
- Number of files/instances mistakenly transformed (FP): 0

Anything else that helps the community prioritize, e.g.:
I'm running the command on Windows 10 under WSL2. I restarted the computer and immediately ran the command in case something else was running interferring. I stopped Docker as well, but I still get the same error.

### Logs:

I don't know where the log file(s) are located

### Additional context

![image](https://github.com/user-attachments/assets/ad805500-7670-47f8-b515-1642c3871f0d)

**Comment by mohab-sameh** [comment]
@kevincam3 You can use `--logs` to generate an error log file. Can you try again and report back?

**Comment by kevincam3** [comment]
I ran this command.  npx codemod@latest nuxt/4/migration-recipe --logs
but I don't see any log file. Where should the log file be saved?

**Comment by mohab-sameh** [comment]
@DmytroHryshyn and I were not able to reproduce this on Mac and Windows. Could it be possibly caused by docker? By the way, we have a [Slack community](https://go.codemod.com/community) if you want to hop in and get support over chat.

**Comment by kevincam3** [comment]
@DmytroHryshyn any idea why the log file is also not being generated or if it should be in some specific location other than the root of the project which is where I am when I run the command.

**Comment by kevincam3** [comment]
Video of the attempt in case something visual stands out.
https://drive.google.com/file/d/1hKel3GL7Aukbwy_QOt4C4xz-89dNQPwM/view?usp=drivesdk
