### ISSUE TITLE
[codemod][FN] nuxt/4/migration-recipe

### ISSUE THREAD

**Issue by xmatthias** [codemod-com/codemod#1255]
#### Original

```ts
./app.config.ts
```

#### Expected

```ts
./app/app.config.ts
```
File is moved into the app directory

#### Actual

```ts
./app.config.ts
```
 (the file is not moved).

### Estimated impact
Numbers about your specific codemod run:

- Total number of files/instances transformed: X
- Number of files/instances missed by the codemod (FN): 1
- Number of files/instances mistakenly transformed (FP): 0

### Logs:

// Please insert the contents of a log file generated by the codemod run here.

### Additional context
`app.config.ts` (usually containing `defineAppConfig`) should be migrated into the app directory - but is missed.

Now i can manually move this in - but in my case, it caused no errors - i just noticed that the app-title (which i'm setting through `app.config.ts` no longer appeared correctly, instead the generic fallback value was set).

Based on the [nuxt migration to v4](https://nuxt.com/docs/getting-started/upgrade#new-directory-structure) - this should be moved into the app directory.

![image](https://github.com/user-attachments/assets/22ac7cf4-e9ed-4682-a573-bb7e09c3cb80)

command used: `npx codemod@latest nuxt/4/migration-recipe`
selecting `nuxt/4/file-structure` - which will _play_ in version 1.0.1

**edit** This is twice as interesting as the codemod does seem to include it - it just isn't acted on.

https://github.com/codemod-com/codemod/blob/a02ae784dd3e8dbce41b370d6e99ab3ec6128c2e/packages/codemods/nuxt/4/file-structure/src/index.ts#L86

**Comment by arybitskiy** [comment]
Thank you for found issue @xmatthias , I created a [PR](https://github.com/codemod-com/codemod/pull/1263) and will let you know once it will be merged.
