### ISSUE TITLE
[docs]: inline markdown in code blocks not rendering correctly

### ISSUE THREAD

**Issue by with-heart** [codemod-com/codemod#1256]
The docs have some code blocks that seem to be using inline markdown to embolden certain parts of the code. That inline markdown isn't being rendered though so the code blocks contain invalid syntax.

Here's [an example from the Codemod 2.0 page](https://docs.codemod.com/guides/building-codemods/codemod2#step-3-use-ast-grep-for-pattern-detection):

https://github.com/codemod-com/codemod/blob/a02ae784dd3e8dbce41b370d6e99ab3ec6128c2e/apps/docs/guides/building-codemods/codemod2.mdx?plain=1#L56-L64

Note that line 62 contains `**astGrep("import { $$$_ } from '@mui/icons-material'"**`. The `**` bold symbols are displayed in the rendered code block:

<img width="764" alt="image" src="https://github.com/user-attachments/assets/d55d3878-cd7d-464c-872a-9524129ecde2">

**Comment by alexbit-codemod** [comment]
thanks, i pushed a fixed for this... you ROCK. keep these coming! <3
