### ISSUE TITLE
[studio] Codemod AI does not respond with anything

### ISSUE THREAD

**Issue by filipditrich** [codemod-com/codemod#1333]
### Issue Description

Select one of:
[ ] ~~Generated codemod is not correct~~
[x] Bug in Codemod Studio
[ ] ~~UI/UX improvement request~~
[ ] ~~Feature request~~

When generating or prompting the AI agent with anything no response is received.

### Steps to Reproduce

1. Open studio
2. Click "Autogenerate with Codemod AI"
3. See new chat "Generate codemod with AI" and chat is loading an answer.
4. Nothing happens

### Actual Results

The button or chat appears to "load" but actually does nothing. No network request or anything logged in the console whatsoever.
<img width="480" alt="Screenshot 2024-09-24 at 4 51 32 PM" src="https://github.com/user-attachments/assets/b91efe4c-8150-41e6-8eaf-290e715b3731">

### Expected Results

Receive a response from the AI agent.

### Technical details

- Tried with multiple browsers, same result.
- Mainly with `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:131.0) Gecko/20100101 Firefox/131.0`

**Comment by mohab-sameh** [comment]
Hi @filipditrich. We had some downtime a few days ago. This should be resolved already. Can you please check and let me know if everything is running smoothly for you?

**Comment by mohab-sameh** [comment]
Closing for now. Please let me know if you run into the same issue again.
