### ISSUE TITLE
[codemod] feature request: rollback on failure

### ISSUE THREAD

**Issue by agamm** [codemod-com/codemod#1362]
### Faulty codemod

1. `react/19/migration-recipe`
2. https://codemod.com/registry/next-15-migration-recipe

### Problem
In this case it changed a bunch of my codebase but failed on this codemod, I would like it to rollback if it fails and not leave my codebase in the failed state with only partial codmods done.

This was originally happening with the next@15 codmod.

**Comment by alexbit-codemod** [comment]
thanks for reporting the feature request.

1. any reason not to use git stash? 

2. also, you can run the individual codemods in the recipe by deselecting the unwanted ones. do you know how? (use spacebar to deselect things when you run the recipe via CLI)

3. and finally, if there is any specific issues with any individual codemod, feel free to open up a github issue and ping our awesome community member, @nishant2253, who built these codemods. 

NOTE: these are NOT the official codemods by next.js team. you can find the official codemods built by vercel team [here](https://nextjs.org/docs/app/building-your-application/upgrading/codemods#150).

**Comment by agamm** [comment]
1. I did eventually use git to roll back, but I'd figure this is something I want codmod to do not me.
2. The next one just ran all of them and failed in the middle of one of them - having an interactive way to rollback or figure out a fix before exiting would be better.
3. Yeah, I will try to go to next 15 when it's a bit more mature it seems like react 19 isn't out yet either - but I'll keep that in mind and report if it continues to happen!

I tried running the official codemod of the vercel team and I think they used those internally, no? I used `npx @next/codemod@canary upgrade latest`

**Comment by alexbit-codemod** [comment]
1 & 2: To @agamm: Got it. Thanks for the explanation. Besides "recipe," we also have another advanced [workflow engine](https://docs.codemod.com/api-reference/git/commit) where we can technically create an advanced recipe where after each individual codemod, changes are committed. This way, if one of the changes is not good, you can revert to previous commits. Would that somehow address what you need? If not, could you explain what your desired experience would be (and how we might build it? reasonable and feasible?)

To @nishant2253: Node modules should have been excluded by default. Do you want to fix this? Feel free to ask folks in the community if you need help.

 3: "I think they used those internally, no?" I don't know what you mean by that. I'm curious how they fell short. How did you find Nishant's codemods in the registry? Why did you decide to give that a try? I would love to know more and see which codemods are missing to create an awesome Next.js upgrade experience.

**Comment by agamm** [comment]
1-2, only if it also tracks things outside the gitignore and manages to roll them back (like dependency package changes).
- Internally it's a good question on how to achieve this, maybe create a separate git history just internally for codmod and use that for rollbacks?

3 - I used the next official docs to run that :) I'
l'll try again in a few weeks to see when it's all more stable.

**Comment by alexbit-codemod** [comment]
awesome! for now, i'll close this issue to keep things easier to navigate and prioritize other tasks, but we'll definitely keep your ideas in mind. cc @mohebifar 

thanks again for taking the time to share them. keep 'em coming! 

also, feel free to join our public [slack community](https://go.codemod.com/community) for more casual convos and brainstorming.
