### ISSUE TITLE
[codemod] `codemod login` fails for first-time users that don't have a `~/.codemod` directory

### ISSUE THREAD

**Issue by spirulence** [codemod-com/codemod#1397]
### Issue Description

Select one of:
[ ] Generated codemod is not correct
[ ] Bug in Codemod Studio
[X] UI/UX improvement request
[ ] Feature request

Codemod studio suggests commands of the form `npx codemod@latest login && ...` when a user clicks "Run via CLI" to try out a codemod against a local set of files.

However, a first-time user of the codemod CLI may run into an error like this when attempting to authenticate with a token using `codemod login` if they do not have a `.codemod` path in their home directory (ie /home/developer/.codemod on POSIX systems).

![CleanShot 2024-12-01 at 22 12 47](https://github.com/user-attachments/assets/816d3ad0-ed91-40c6-8899-880bf49d58cd)
### Steps to Reproduce

1. Run `npx codemod@latest login` on a POSIX system that has NodeJS installed but does not yet have a working codemod CLI installation. For a docker one-liner, use `docker run -it node:20 npx --yes codemod@latest login`.

### Actual Results

You'll see an error relating to the missing directory, like `Error: ENOENT: no such file or directory, scandir '/root/.codemod'`

### Expected Results

You should see the error message about how a `keytar` helper isn't present and needs to be installed in order for the best operation. You can get this result in docker by including a "mkdir" command in the one-liner, like `docker run -it node:20 sh -c "mkdir -p /root/.codemod && npx --yes codemod@latest login"`

![CleanShot 2024-12-01 at 22 20 54](https://github.com/user-attachments/assets/b79bb504-5252-42e7-afdf-5445596979a6)

(the xdg-open error is a separate issue #1046  that the team seems to already be aware of)

### Technical details

- NodeJS 20 docker image (also on my local Ubuntu 24 development VM)
- Codemod CLI latest version.

**Comment by arybitskiy** [comment]
Fixed in #1385

**Comment by mohab-sameh** [comment]
@all-contributors add @spirulence for bugs

**Comment by spirulence** [comment]
closed #1398 in favor of #1401

**Comment by mohab-sameh** [comment]
@spirulence cleanup: closing since your previous comment didn't. Let me know if you'd like to reopen this issue.
