### ISSUE TITLE
[codemod][FP/FN] @next/codemod@canary

### ISSUE THREAD

**Issue by DanOnCall** [codemod-com/codemod#1431]
### Faulty codemod

Codemod name: `@next/codemod@canary`
Link: https://nextjs.org/docs/app/building-your-application/upgrading/version-15
Task: Upgrade project to Next.js v15

### Sample code snippets

A component with the following `type` definition was updated correctly to use `Promise` as the type wrapper for `params` in a Next.js React Server Component:

```typescript
type PageProps = {
  params: { article: string };
};
```

![image](https://github.com/user-attachments/assets/5a711d5e-81b5-42c3-be2e-3b399c44e2dc)

However, when a `type` definition included a type union, the `Promise` wrapper was not applied:

```typescript
type PostLayoutProps = {
  params: { article: string };
} & PropsWithChildren;
```

![image](https://github.com/user-attachments/assets/dc303cd2-80c3-47ae-90b3-20ce67e622f4)

#### Original

```ts
type PostLayoutProps = {
  params: { article: string };
} & PropsWithChildren;
```

#### Expected

```ts
type PostLayoutProps = {
  params: Promise<{ article: string }>;
} & PropsWithChildren;
```

#### Actual

```ts
type PostLayoutProps = {
  params: { article: string };
} & PropsWithChildren;
```

**Comment by alexbit-codemod** [comment]
Seems that this is a next codemod. Not built/maintained by us (Codemod). 
Do u mind moving this to the right next repo? Thanks for your contributions to codemods and Codemod. ❤️🍻
