### ISSUE TITLE
Cannot sign in using Cursor

### ISSUE THREAD

**Issue by espenbye** [codemod-com/codemod#437]
The issue arises when attempting to authenticate the Codemod extension in [Cursor](https://cursor.sh). After successful authentication on the web, the website attempts to redirect using the `vscode://` URL scheme. However, the Cursor application does not recognize this URL scheme. A workaround has been found where manually changing the URL scheme to `cursor://` allows the redirect to work as expected.

## Steps to Replicate

1. Open the Cursor application.
2. Install the Codemod extension within the Cursor application.
3. Click on the 'Sign In' button within the Codemod extension.
4. Authenticate with the required credentials on the web.
5. After successful authentication, the website attempts to redirect using the `vscode://` URL scheme.

At this point, the Cursor application fails to recognize the `vscode://` URL scheme and thus Codemod cannot sign in.

**Comment by mohab-sameh** [comment]
hi @espenbye I hope the issue got resolved for you. Was it a reproducible bug we should look into?

**Comment by espenbye** [comment]
Hi @mohab-sameh! Solved it by copying the redirect `vscode://` URL after authentication and changed it to `cursor://`. So now I'm logged in, but yes - it should probably be a bit easier :)

**Comment by mohab-sameh** [comment]
@all-contributors add @espenbye for bug report

**Comment by hbjORbj** [comment]
@espenbye 

Thanks for the report. This is actually very important feedback. We will make sure to support Cursor users.

**Comment by hbjORbj** [comment]
@espenbye Thanks to your great feedback, I opened a [PR](https://github.com/codemod-com/codemod/pull/460) to support Cursor users for the authentication flow. Feel free to check it and review it. We are aiming to merge it by the end of tomorrow.

**Comment by hbjORbj** [comment]
@espenbye We just merged the PR! You will now be able to authenticate from the extension in Cursor with no trouble! Any other feedback is appreciated! Thanks a lot!
