### ISSUE TITLE
[codemod request] types-react: remove deprecated ReactHTML and ReactSVG

### ISSUE THREAD

**Issue by alexbit-codemod** [codemod-com/codemod#642]
on behalf of [eps1lon](https://github.com/eps1lon):

" `ReactHMTL` and `ReactSVG` were related to `createFactories` but we found usage using it as a list of possible built-in browser element types.

We now have `HTMLElementType` and `SVGElementType` which can be used instead of `keyof ReactHTML` and `keyof ReactSVG` respectively.

Needs real world codebase with usage to test on."

> Note: The example section helps codemod contributors identify all the transformation patterns that this codemod should handle. Repeat before/after snippets for every transformation example you can find.

### Code before transformation

```
//insert your code before transformation here
```

### Code after transformation

```
//insert the expected **correct** output here
```

### Applicability Criteria

Which types-react versions include the deprecated pattern?

### Additional context or links
[Add any other context about the problem here. This might include extra considerations, edge cases, relevant business logic, existing migration guides, relevant links, etc.](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-deprecated-typescript-types)

**Comment by arshcodemod** [comment]
@alexbit-codemod the current react-beta guide doesn't have a mention of this?
"ReactHMTL and ReactSVG were related to createFactories but we found usage using it as a list of possible built-in browser element types."

**Comment by mohab-sameh** [comment]
Okay we tried again and got [this codemod](https://go.codemod.com/IlB72Qo). It fixed the import statement, but the tag is not fixed.

We followed @arybitskiy's suggestions shown [here](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4a100fd37c4de594b772d8c2f09a788098d34314) and [here](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/64451).
