### ISSUE TITLE
[codemod request] Nuxt 4: shared prerender data

### ISSUE THREAD

**Issue by mohab-sameh** [codemod-com/codemod#715]
This codemod should ensure that any unique key of your data is always resolvable to the same data. For example, if you are using `useAsyncData` to fetch data related to a particular page, it should be changed to a key that uniquely matches that data. (`useFetch` should do this automatically for you.)

### Code before transformation

```ts
const route = useRoute()
const { data } = await useAsyncData(async () => {
  return await $fetch(`/api/my-page/${route.params.slug}`)
})
```

### Code after transformation

```ts
const route = useRoute()
const { data } = await useAsyncData(route.params.slug, async () => {
  return await $fetch(`/api/my-page/${route.params.slug}`)
})
```

### Applicability Criteria

Nuxt 3 to Nuxt 4

### Additional context or links
- [Reference in migration guide](https://nuxt.com/docs/getting-started/upgrade#shared-prerender-data)

**Comment by 35C4n0r** [comment]
/attempt #715

@mohab-sameh can you assign it to me, I would like to try this out.

**Comment by mohab-sameh** [comment]
@all-contributors add @35C4n0r for Code
