### ISSUE TITLE
[codemod][new] Web3.js - migration to v4.x

### ISSUE THREAD

**Issue by alexbit-codemod** [codemod-com/codemod#908]
### Migration details
[Link to upgrade guide](https://docs.web3js.org/guides/web3_upgrade_guide/x/)

- [ ] [web3.providers](https://docs.web3js.org/guides/web3_upgrade_guide/x/providers_migration_guide)
    - [ ]  HttpProvider - [CS Link](https://go.codemod.com/q8aFwuh)
    - [ ]  WebSocketProvider - CS link
- [ ] [web3.eth.ens](https://docs.web3js.org/guides/web3_upgrade_guide/x/web3_eth_ens) - CS link
- [ ] [web3.eth](https://docs.web3js.org/guides/web3_upgrade_guide/x/web3_eth_migration_guide)
  - [ ] deprecate-web3-core-promievent - CS link
- [ ] [web3.eth.Contract](https://docs.web3js.org/guides/web3_upgrade_guide/x/contracts_migration_guide) - CS link
- [ ] [web3.eth.accounts](https://docs.web3js.org/guides/web3_upgrade_guide/x/accounts_migration_guide) - CS link
- [ ] [web3.eth.abi](https://docs.web3js.org/guides/web3_upgrade_guide/x/abi_migration_guide) - CS link
- [ ] [web3.eth.iban](https://docs.web3js.org/guides/web3_upgrade_guide/x/web3_eth_iban) - CS link
- [ ] [web3.eth.personal](https://docs.web3js.org/guides/web3_upgrade_guide/x/personal_migration_guide) - CS link
- [ ] [web3.eth.subscribe](https://docs.web3js.org/guides/web3_upgrade_guide/x/subscribe_migration_guide) - CS link
- [ ] [web3.*.net](https://docs.web3js.org/guides/web3_upgrade_guide/x/net_migration_guide) - CS link
- [ ] [web3.utils](https://docs.web3js.org/guides/web3_upgrade_guide/x/web3_utils_migration_guide) - CS link

----
To contributors working on this task:

- [ ] **Framework Expert**:  For each codemod use case in this migration, provide the Codemod Studio link ([example](https://go.codemod.com/sme-input)) with detailed specifications. Include before/after pairs, transformation logic in comments, and edge cases. Even if the transformation is tricky, provide instructions on detecting the patterns. This helps estimate the effort needed and guides developers to the areas requiring manual changes.

- [ ] **Codemod Creator**: [Build](https://go.codemod.com/build-codemod-docs) and [publish](https://go.codemod.com/codemod-publish-doc) quality codemods that handle most edge cases. False negatives are acceptable, but there should be no false positives.

- Questions? -> [Community](https://go.codemod.com/community)

**Comment by mohab-sameh** [comment]
Deprioritized. Closing for now.
