### ISSUE TITLE
[codemod][new] svelte - migration to svelte 4

### ISSUE THREAD

**Issue by arshcodemod** [codemod-com/codemod#928]
### Migration details
[[Link to upgrade guide](https://svelte.dev/docs/v4-migration-guide)]

- [ ] codemod-componenttypedeprecated- [[Codemod Studio Link](https://go.codemod.com/psiEdeu)]
- [ ] codemod-strictertypes - [[Codemod Studio Link](https://go.codemod.com/nQWo6WG)]
- [ ] codemod-customelements - [[Codemod Studio Link](https://go.codemod.com/ydqpXPo)]

----
To contributors working on this task:

- [ ] **Framework Expert**:  For each codemod use case in this migration, provide the Codemod Studio link ([example](https://go.codemod.com/sme-input)) with detailed specifications. Include before/after pairs, transformation logic in comments, and edge cases. Even if the transformation is tricky, provide instructions on detecting the patterns. This helps estimate the effort needed and guides developers to the areas requiring manual changes.

- [ ] **Codemod Creator**: [Build](https://go.codemod.com/build-codemod-docs) and [publish](https://go.codemod.com/codemod-publish-doc) quality codemods that handle most edge cases. False negatives are acceptable, but there should be no false positives. Even if the transformation is tricky, build a codemod that can detect and add comments to guide developers to the areas needing manual changes.

- Questions? -> [Community](https://go.codemod.com/community)

**Comment by mohab-sameh** [comment]
Closing as stale.
