### ISSUE TITLE
[www] Broken Link on landing page header for CLI

### ISSUE THREAD

**Issue by unclebay143** [codemod-com/codemod#984]
### Issue Description

Select one of:
[ ] Generated codemod is not correct
[ ] Bug in Codemod Studio
[x] UI/UX improvement request
[ ] Feature request

A quick description of the issue you ran into.

A link is broken in the codemod header in the landing page

### Steps to Reproduce

1. Goto the landing page
2. Hover on platform and click on the CLI option
![image](https://github.com/codemod-com/codemod/assets/58919619/46aad127-273d-4a45-89e1-69b96a8572ff)

### Actual Results

showing a 404 page
![image](https://github.com/codemod-com/codemod/assets/58919619/798c7947-91a3-4117-828b-9d072a375228)

### Expected Results
first time here, not sure.

### Technical details

- Browser version, screen recording, console logs, network requests (optional).
- Node.js version
- Anything else that you think could be an issue.

**Comment by alexbit-codemod** [comment]
you ROCK. thanks for the great catch.

##985

**Comment by alexbit-codemod** [comment]
Thanks again @unclebay143
